### ISSUE TITLE
F-M2-2F API access to data (gathering of data)

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#19]
Backend API Definition for accessing the shared data.

**Comment by amedranogil** [comment]
Data is the data that the patient has shared with the Investigator.
This API provide access to EXTERNAL (outiside openDSU framework) processes such as ML, AI, DSS, ... to access the information.

**Comment by amedranogil** [comment]
![image](https://user-images.githubusercontent.com/6515064/120008211-05253680-bfdb-11eb-9d00-a61147da0551.png)

**Comment by amedranogil** [comment]
> Data is the data that the patient has shared with the Investigator.

shared through DSUs, and the dPermissioning process.

> This API provide access to EXTERNAL (outiside openDSU framework) processes such as ML, AI, DSS, ... to access the information.

Because the data custody needs to be maintained, this external API should be secured and managed by the researcher.

Any application with the proper credentials should be able to collect FHIR data from this API. 
This API could be seen as a FHIR server, ideally, but other simpler solutions for the MVP such as just returning the whole data set can work.
