### ISSUE TITLE
F-M3-1F My Data (IoT data)- Integrated

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#25]
UI for reviewing the collected data from IoT Devices, integrated with the DSU system collection.

**Comment by elubilu** [comment]
I believe this is the UI - https://www.figma.com/proto/jdEbrfVE0o42mEAKybFXDc/Personalized-Medicine-BUENO-(Copy)-(Copy)?embed_host=share&kind=&node-id=505%3A441&page-id=0%3A1&scaling=scale-down 
related to this task. But from the UI the feature is not clear to me. Whenever I click on **Show Data** button, it shows a chart which is unclear to me. Can you please provide further clarification? @nliappas  @amedranogil

**Comment by nliappas** [comment]
yes this is the UI. It should have the 2 sections as in the mockup: my documents, my sources. after the click show data it should open a new page able to display various content. the diagram is for demo purposes. it should display whatever data is the input, not only diagrams. We have the screen for the Alpha Version, this should be now be connected with the back-end, maybe we can pass some dump data of the IoT device we are already using.

**Comment by elubilu** [comment]
Ok, however, i have following points to clarify first: 

- **My Documents** section will show the same data points as Health Provider Agent for example: ECG value, Heart Rate, Body Temperature, Blood Pressure, SpO2 and Respiratory Frequency. Will it work? 
- **My Sources** section is currently stated list of hospitals or clinical sites. Shouldn’t it be the list of clinical trials that participated by the patient  instead of hospitals or clinical trails?

**Comment by elubilu** [comment]
Is there any update on the UI? I am waiting for the UI to integrate based on data model. @nliappas  @amedranogil

**Comment by nliappas** [comment]
UI mockup and code are updated. check the link in the projects' section.
